### ISSUE TITLE
Docker image github action failing

### ISSUE THREAD

**Issue by goneall** [spdx/tools-java#128]
From a scan of the logfiles, it looks like it might be an issue with the new version.

Note - I did have an issue with the wrong commit on the branch earlier which I fixed with some forced pushes to the repo.  I don't know if that might be a factor in the failures.

Attached are the logs.
[logs_187.zip](https://github.com/spdx/tools-java/files/11456230/logs_187.zip)

**Comment by goneall** [comment]
@heliocastro - could you take a look at this issue and see if you can identify the cause?

**Comment by goneall** [comment]
Here's the last few lines of the output:

```
Dockerfile:14
--------------------
  13 |     # BUILD
  14 | >>> RUN --mount=type=cache,target=/root/.m2 \
  15 | >>>     --mount=type=bind,source=$PWD,target=/build,rw \
  16 | >>>     mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install \
  17 | >>>     && mkdir -p /usr/lib/java/spdx \
  18 | >>>     && cp target/tools-java-$TOOLS_JAVA_VERSION-jar-with-dependencies.jar /usr/lib/java/spdx/
  19 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install     && mkdir -p /usr/lib/java/spdx     && cp target/tools-java-$TOOLS_JAVA_VERSION-jar-with-dependencies.jar /usr/lib/java/spdx/" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install     && mkdir -p /usr/lib/java/spdx     && cp target/tools-java-$TOOLS_JAVA_VERSION-jar-with-dependencies.jar /usr/lib/java/spdx/" did not complete successfully: exit code: 1
```

**Comment by heliocastro** [comment]
@goneall Looking on to it.

**Comment by heliocastro** [comment]
@goneall You change for version 1.1.6 but not changed inside Docker, so still pointing to 1.1.5-SNAPSHOT ( last tag )

this part of the github action:
```yaml
      - name: Set environment variables                                                                                                                                          
        run: |                                                                                                                                                                   
          echo "ORG_BASE_NAME=${GITHUB_REPOSITORY}" >> $GITHUB_ENV                                                                                                               
          echo "TOOLS_JAVA_VERSION=${GITHUB_REF_NAME/v/}" >> $GITHUB_ENV 
```
So GITHUB_REF_NAME was expecting a tag v1.1.6, which not exists yet.
