### ISSUE TITLE
How can i refer 2 spdxs in third spdx file and access all the packages information from 3rd spdx file

### ISSUE THREAD

**Issue by rakeshsrinivasa** [spdx/tools-java#131]
Suppose Assume that i have a spdx file called "spdx_1.yaml" and another one called "spdx_2.yaml" . Both these spdx files has certain packages.  Now i want to create another spdx file (call spdx_3.yaml) which just refers spdx_1 and spdx2 yaml files available locally in the same folder.

Now using spdx-tools java i need to access all the packages available in spdx_1 and spdx_2 yamls Via spdx_3.yaml. 

Below is my questions
1. 
I am facing difficulties in forming spdx_3.yaml .Please do verify and help me
[github.zip](https://github.com/spdx/tools-java/files/11910754/github.zip)

2. How can i access all the packages present in spdx_1 and spdx_2 yaml via spdx_3.yaml in spdx-tools java

Thanks in advance

**Comment by rakeshsrinivasa** [comment]
@goneall  Any comments/suggestions on above ?

**Comment by goneall** [comment]
@rakeshsrinivasa If you want to refer to packages in spdx_1 and spdx_2, you would use the `externalDocumentRefs` with document namespaces from spdx_1 and spdx_2.  For example:

```
externalDocumentRefs:
  - externalDocumentId: "DocumentRef-spdx_1"
    checksum:
      algorithm: "SHA1"
      checksumValue: "[the checksum for spdx_1 yaml file]"
    spdxDocument: "http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301"
```

You would then refer to the package using the syntax `[DocumentRef]:[SpdxID]`, for example: `DocumentRef-spdx_1:SPDXRef-Package-1`.
